server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true

whatsapp:
  access-token: "EAAXw9TM5ZAGUBQwIvZAyXoGZAHx1Mc2ZAzy1JykiALJy0nXTQfAzyZA1ZBPZA3Aq1uCh11uaCCKa1kYnRZAZCLaYv7THHrLn6hVtWOmT9DXSJJmUb7ZBZBpRSZCixtVGU6VwFhUex1UiWqsxKuP63bTx67Jk6v6EErkWLXJSJS8mAeIKhR6uBouZBsaNac2DaeCyQVTIgptPrdWEx1ZBRZCCgidZAdpKKIGGUzrySWCmRCFZCu1FhS258mZCVdUCD77IPa712VhyOKwp7VnkaPTxnQLZCT9ZC5FYREwj"
  phone-number-id: "978744951997011"
  verify-token: "playmatch"
  app-secret: "playmatch"
  api-version: "v25.0"
  normalize-argentine-numbers: true

mcp-client:
  url: http://localhost:8082
